### ISSUE TITLE
(docs) Configure ReadTheDocs webhook for automated docs builds

### ISSUE THREAD

**Issue by philiplinden** [Nate-Wilkins/video-pipeline#1]
ReadTheDocs automatically configured a webhook integration. This webhook can be configured from the RTD side here: readthedocs.org/api/v2/webhook/video-pipeline/83880/

Configure when new RTD builds are kicked off  in GitHub integration settings. 

Use the RTD docs for instructions: https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by Nate-Wilkins** [comment]
Weebhook is setup 🎉 

![image](https://user-images.githubusercontent.com/2957868/57055333-b7993c80-6c4f-11e9-80ef-59336b12026f.png)
